spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: post-service
  liquibase:
    default-schema: blog
#    change-log: classpath:db/changelog/liquibase-changelog:xml