server:
  port: 8094
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/postdb
    username: Admin
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
    default-schema: blog
application:
  file:
    uploads:
      photos-output-path: ./uploads