server:
  port: 8092
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: userdb
      username: Admin
      password: Admin@123
      authentication-database: admin
application:
  file:
    uploads:
      photos-output-path: ./uploads

